services:
  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.35.0
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
  prometheus:
    # A prometheus image from docker hub
    image: prom/prometheus:v2.39.1

    # A volume that mounts the ~/monitoring/prom.yaml file
    # into the container, to tell prometheus how to reach cadvisor
    volumes:
    - $HOME/monitoring/prom.yaml:/etc/prometheus/prometheus.yml

    # Add a new volume with the alerts definition
    - $HOME/monitoring/alerts.yaml:/etc/prometheus/alerts.yml

    # Expose port 8080 to access the prometheus UI on the browser
    ports:
      - "8080:9090"

  alertmanager:
    # Alertmanager docker image
    image: prom/alertmanager:v0.23.0

    # Mounts the alertmanager-config.yaml file
    volumes:
      - "$HOME/monitoring/alertmanager-config.yaml:/etc/alertmanager/alertmanager.yml"
