scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s # Pull metrics every 5 seconds
  static_configs:
  - targets:
    # `cadvisor` is the name that was defined in the docker-compose.yaml
    # describing the configurations for cadvisor.
    - cadvisor:8080

# How often to evaluate alerts
global:
  evaluation_interval: 20s

# Where to find the definition of the alerts in the Prometheus container
rule_files:
  - /etc/prometheus/alerts.yml

# Tell Prometheus how to reach Alertmanager
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        # alertmanager is the name defined in Docker Compose, at services.alertmanager
        # alertmanager runs by default on port 9093
        - targets: [ 'alertmanager:9093' ] 